defaultLanguage: en
languages:
  - code: en
    name: English
    localName: English
    dir: ltr
    enabled: true
  - code: es
    name: Spanish
    localName: Español
    dir: ltr
    enabled: true
  # Future languages can be added here
  # - code: fr
  #   name: French
  #   localName: Français
  #   dir: ltr
  #   enabled: false
  # - code: de
  #   name: German
  #   localName: Deutsch
  #   dir: ltr
  #   enabled: false
  # - code: ar
  #   name: Arabic
  #   localName: العربية
  #   dir: rtl
  #   enabled: false